### PR TITLE
Switch from rulinalg to nalgebra for SVD

### LINKED ISSUE #412: getting a Projection by from_control_points makes program freezing
This occurs every time you run the program. Here is the minimal code.
```Rust
fn main() -> Result<(), Box<dyn Error>>{
    println!("get a projection from control points...");
    let from = [(0.0, 0.0), (250.0, 17.481735), (7.257017, 82.94814), (250.0, 104.18543)]; 
    let to = [(0.0, 0.0), (249.0, 0.0), (0.0, 105.0), (249.0, 105.0)];
    let projection = Projection::from_control_points(from, to);
    match projection {
        Some(_p) => println!("new projection"),
        None => println!("failed")
    }
    Ok(())
}
```
Here is all the output I get, nothing else: 
image
I think `Projection::from_control_points` should either return Some(_) or None, rather than just keeps freezing. 
Thanks all the work you have done! This may be a bug, please someone check it.

### PR DESCRIPTION
**Pull request by Palladinium**
Fixes #412

This is working fine on a private project, but I don't know much about linear algebra and there aren't nearly enough test cases to ensure this doesn't break a bunch of stuff, so someone who's more knowledgeable should double check this.

### CODE REVIEW

**Comment by Palladinium** [comment]
I've been spending some time testing and debugging this branch, as well as reading into the linear algebra behind the logic here, and I'm now pretty reasonably confident I'm doing this right.

It should be safe to merge, but once again it'd be good if someone with a better background in mathematics could double-check this.

**Comment by ciuncan** [comment]
Today I ran `cargo audit` on our repo and the only dependency with vulnerability was showing up as `imageproc` due to `rulinalg`. I am glad that someone worked on replacing `rulinalg` with `nalgebra`. 

```
❯ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 366 security advisories (from /Users/ceyhun/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (356 crate dependencies)
Crate:         rulinalg
Version:       0.4.2
Title:         Lifetime boundary for `raw_slice` and `raw_slice_mut` are incorrect
Date:          2020-02-11
ID:            RUSTSEC-2020-0023
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0023
Solution:      No safe upgrade is available!
Dependency tree: 
rulinalg 0.4.2
└── imageproc 0.22.0
    └── raijin 0.2.0

Crate:         rulinalg
Version:       0.4.2
Warning:       unmaintained
Title:         rulinalg is unmaintained, use nalgebra instead
Date:          2020-02-11
ID:            RUSTSEC-2020-0147
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0147

error: 1 vulnerability found!
warning: 1 allowed warning found
[1]    7589 exit 1     cargo audit
```

**Comment by timbod7** [comment]
I've tried out this PR, and it works more reliably the the code it replaces.

**Comment by theotherphil** [comment]
Thanks! Sorry about the very long delay.

**Comment by ciuncan** [comment]
Thank you guys for the very quick test and merge! When can we expect a release including this merge?

**Pull request merged**
