### PR TITLE
fix `text_size`

### PR DESCRIPTION
**Pull request by cospectrum**
First I tried `h = h.max(bb.min.y + bb.height());`. But then I think I found a better solution.
Looks good when using English and Japanese text. And some useful distance at the bottom of the text. You can try on my branch.
Relates: https://github.com/image-rs/imageproc/issues/687

### CODE REVIEW

**Comment by cospectrum** [comment]
I think `clippy` should be optional because we use the `nightly` version to get the latest features and improve the code. 
But there are no "allowed to fail" jobs on `github-actions`, thus, we will live with the red status

**Comment by cospectrum** [comment]
It's not that bad. I see that it discovered unnecessary lifetimes and stuff. We just have to fix it every couple of months.

**Comment by cospectrum** [comment]
Maybe we can add more versions to clippy matrix
```yaml
matrix:
    toolchain: [nightly]
```

**Comment by cospectrum** [comment]
> Maybe we can add more versions to clippy matrix
> 
> ```yaml
> matrix:
>     toolchain: [nightly]
> ```

No, stable `clippy` doesn't understand test code with nightly features

**Comment by cospectrum** [comment]
I left text rendering unchanged, didn't find any fatal errors.

`rect.height() == font.height()`.

font

**Comment by theotherphil** [comment]
Thanks!

it would be nice to extend the text regression test to include the issue this is fixing: https://github.com/image-rs/imageproc/blob/54573dabc28e0fdd8f978843e253d06bc763cf14/tests/regression.rs#L810

**Comment by cospectrum** [comment]
Ofc. I will write proptests to ensure that text is always rendered inside this rectangle.

**Comment by cospectrum** [comment]
And now I have found a counterexample for the X position in `draw_text` itself (first `j`).
```rs
let x = 62;
let y = 21;
let scale = 78.0932;
let text = "jnenuoltqjylzcbvcc";
```
font

**Comment by cospectrum** [comment]
I wonder if this is a bug in the `ab_glyph` bbox or a rounding error in the `imageproc`?

**Comment by cospectrum** [comment]
Maybe the origin of the first glyph? its (0, font.ascent())

**Comment by cospectrum** [comment]
I tried to fix it, but it requires replacing the `text.png` sample from the regression tests.

**Comment by cospectrum** [comment]
`proptest` passed for english text with numbers

**Comment by theotherphil** [comment]
The test image can be regenerated by running

`REGENERATE=1 cargo test`

**Comment by cospectrum** [comment]
Are you familiar with OpenType glyphs? 
I didn't plan to change `draw_text` at all. But now I'm shifting all glyphs to the right by `abs(h_side_bearing)` of the first glyph, because some glyphs go beyond of `Rect.at(x, y)`, and it's not just a floating point error.

**Comment by cospectrum** [comment]
I think that despite moving to the right, all relative distances will remain the same as in the previous implementation.

**Comment by cospectrum** [comment]
For example, in the previous implementation, the drawing of `j` with `(x, y) = (0, 0)` will go beyond the image.

**Comment by cospectrum** [comment]
We can go the other way. We can keep the starting point at 0, that is, no change in the `draw_text` implementation. And we can document that in `draw_text`. 
Instead, we will change my new tests so that the "checked" rectangle itself takes into account the negative bearing.
What do you think?

**Comment by cospectrum** [comment]
We can also try to add the horizontal `bearing` to the origin only if it is negative.

**Comment by theotherphil** [comment]
I’m not familiar with OpenType.

Any of these options seems fine - let’s go with relaxing the test to allow for negative side bearings if you have no preference.

**Comment by cospectrum** [comment]
Sure, one moment

**Comment by cospectrum** [comment]
Done

**Comment by cospectrum** [comment]
Finally, almost 1 day is spent.

**Comment by cospectrum** [comment]
I added `+1` because otherwise `rect.contains` will fail

**Comment by theotherphil** [comment]
Thanks a lot!

**Pull request merged**
