### PR TITLE
add a general nxm convolution filter (a generalization of filter3x3)

### PR DESCRIPTION
**Pull request by vsuryamurthy**
This PR is a generalization of the filter3x3 and extends to odd shaped kernels of dimensions nxm.

### CODE REVIEW

**Comment by cospectrum** [comment]
Maybe we can just call it `filter`? 🤔

**Comment by cospectrum** [comment]
Or we can expose it to users as a Kernel method. `clamped_filter`, for example.

**Comment by vsuryamurthy** [comment]
Sure, either works. What would be the prefernce?

**Comment by cospectrum** [comment]
> Sure, either works. What would be the prefernce?

Let's ask the owner @theotherphil. Do you have any preferences or maybe some criticism of this pr?

**Comment by cospectrum** [comment]
The strange thing is that this only works for odd sizes. I have an implementation of 2d convolution in Rust by matrix multiplication (compatible with [torch](https://pytorch.org/docs/stable/generated/torch.nn.functional.conv2d.html)), and the kernels are of any size.

**Comment by theotherphil** [comment]
Thanks for the PR. I’m not sure about the filternxm function - filter3x3 exists mainly because it initially had a special cased implementation. I’d accept a PR to add a clamped_filter function to Kernel.

**Pull request closed without merging**
