### PR TITLE
Add `proptests` for `filter/mod.rs`

### PR DESCRIPTION
**Pull request by cospectrum**

### CODE REVIEW

**Comment by ripytide** [comment]
Looks good to me. As an aside, I wonder if there are any functions in the library that are perfect inverses on one another as that would make for some really neat property tests, testing for equality after applying a function and then its inverse.

**Comment by cospectrum** [comment]
There will also be more checks under sanitizers or with `debug_assert`. `Miri` is too slow for this

**Comment by theotherphil** [comment]
Thanks! It’s a bit clunky to have proptest and quickcheck used in the same crate - would be nice to move the quickcheck uses across at some point.

**Comment by cospectrum** [comment]
I think `proptest` is a more powerful lib, I can get rid of `quickchek`, but its in the public api behind the feature.

**Comment by theotherphil** [comment]
I expect it’s not widely used and I’m fine with the API change if it’s easy for users to migrate.

**Comment by cospectrum** [comment]
Why do we even have `property_testing` in the public api?

**Comment by cospectrum** [comment]
It's not used in integration tests, so it doesn't make sense to me.

**Comment by theotherphil** [comment]
It's in the public API to help users test their own functions. It's been used in at least one other crate but I'm not sure how widely it's used now.

**Pull request merged**
