### PR TITLE
Remove unnecessary allocations

### PR DESCRIPTION
**Pull request by cospectrum**
The only public change: `convex_hull`.

### CODE REVIEW

**Comment by theotherphil** [comment]
Thanks for the PR. Does replacing a nested loop with Image::from_fn have any impact on the image filtering benchmarks?

**Comment by cospectrum** [comment]
`Image::from_fn` iterates in the same order (row-major, cache friendly), so it should be the same. Plus, you don't have to think about the row-major vs col-major every time.

**Comment by cospectrum** [comment]
> `Image::from_fn` iterates in the same order (row-major, cache friendly), so it should be the same. Plus, you don't have to think about the row-major vs col-major every time.

Hmm, not really. A small regression. It seems that the compiler cannot optimize the mutable lambda

**Comment by cospectrum** [comment]
Or the iterators are to blame.

**Comment by cospectrum** [comment]
A couple of minutes. I'll refactor the lookup tables incrementally

**Comment by cospectrum** [comment]
@theotherphil, Now I think my `bilateral_filter` bench is better than the `master` (both allocs and speed).

**Comment by theotherphil** [comment]
Great, thanks!

**Pull request merged**
