### PR TITLE
Add a `CONTRIBUTING.md` and refactor the `README.md`

### LINKED ISSUE #526: Testing requires nightly?
It seems that running `cargo test` requires nightly. I assume that it is on purpose, but it is a bit unexpected. Maybe a note in README would help?

### PR DESCRIPTION
**Pull request by ripytide**
Should close #526

### CODE REVIEW

**Comment by ripytide** [comment]
I've just seen the `README.md` has a contributing section, perhaps the best move would be to move that information into the `CONTRIBUTING.md` and replace it with a link to the `CONTRIBUTING.md`?

**Comment by ripytide** [comment]
I've also added the remaining undocumented crate features to the `README.md`

**Comment by theotherphil** [comment]
This is a good idea but I want to tinker with the wording a bit so I’ll merge a jointly-authored PR with a variation on this soon.

**Comment by theotherphil** [comment]
Tweaked version merged in https://github.com/image-rs/imageproc/pull/640.

I'd assumed that adding a co-authored-by comment on the PR description in GitHub would add you as a co-author but it looks like not.

**Comment by ripytide** [comment]
I think you have to add a `Co-authored-by: Name <email>` in the commit message after a newline according to the [docs](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) to get GitHub to show both user-icons.

But it doesn't really matter, I don't mind.

**Pull request closed without merging**
