### PR TITLE
Switch from quickcheck to proptest

### LINKED ISSUE #626: migrate from `quickcheck` to `proptest`
Discussed in #599

### PR DESCRIPTION
**Pull request by ripytide**
Fixes #626

### CODE REVIEW

**Comment by cospectrum** [comment]
You didn't disable miri on proptests

**Comment by cospectrum** [comment]
You can move them to local `mod proptests`

**Comment by ripytide** [comment]
Some utility functions were used in both normal tests and protests so I found it easier to just leave them together, but I suppose the best solution would be to add another shared `utils` module.

**Comment by cospectrum** [comment]
You can make some helpers from `mod tests` public

**Comment by ripytide** [comment]
Okay I've extracted all proptests into their own `proptest` modules which is definitely much nicer. Thanks @cospectrum for the pointer on making testing utilities `pub`.

**Comment by cospectrum** [comment]
Lgtm

**Comment by theotherphil** [comment]
A nice improvement, thanks. I’ll merge after the version issue is resolved.

**Comment by cospectrum** [comment]
merge master, for example

**Comment by cospectrum** [comment]
Details -> rerun, probably

**Comment by theotherphil** [comment]
Thanks!

**Pull request merged**
