### PR TITLE
Expand `stetch_contrast()` to color images also using `u8`

### PR DESCRIPTION
**Pull request by ripytide**
Ideally we'd want to use the `Enlargeable` trait currently private inside `image` to make this work for all types rather than just `u8`, but this is still an improvement that should be good enough for https://github.com/image-rs/image/issues/2238.

### CODE REVIEW

**Comment by ripytide** [comment]
It seems we need to bump the minimal rust version now since one of our dependencies, I think `bitstream-io` now requires `v1.79`

**Comment by theotherphil** [comment]
Thanks! What impact does this have on function run time for the greyscale case?

**Comment by ripytide** [comment]
Looks like impact:
Before PR:
```
test contrast::benches::bench_stretch_contrast                                        ... bench:         660.08 ns/iter (+/- 2.24)
test contrast::benches::bench_stretch_contrast_mut                                    ... bench:           0.25 ns/iter (+/- 0.00)
```
After PR:
```
test contrast::benches::bench_stretch_contrast                                        ... bench:         658.86 ns/iter (+/- 7.36)
test contrast::benches::bench_stretch_contrast_mut                                    ... bench:           0.25 ns/iter (+/- 0.00)
```

**Comment by theotherphil** [comment]
Thanks!

(Aside: it looks like the _mut variant of that benchmark is optimising out the function and so not actually running .)

**Pull request merged**
