### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by TianyiShi2001**
Fixed clippy warnings

### CODE REVIEW

**Comment by theotherphil** [comment]
The CI failures are because we check that the code formatting matches that returned by cargo fmt:

image

**Comment by TianyiShi2001** [comment]
Sorry, I was working on [image-rs/image](https://github.com/image-rs/image) which does not use `rust fmt`. Now I've run it.

**Comment by theotherphil** [comment]
LGTM, but there's a merge conflict to be resolved before I can merge the PR.

**Comment by theotherphil** [comment]
Thanks!

**Pull request merged**
