### PR TITLE
Implement Kapur's algorithm for binary thresholding (#696)

### PR DESCRIPTION
**Pull request by oqpvc**
Kapur's algorithm uses an entropy approach to find a good segmentation threshold for gray images.

This implementation of Kapur's algorithm sticks closely to the notation of the original article (https://doi.org/10.1016/0734-189X(85)90125-2), so it is much easier to check for correctness. We also avoid a double loop, so this only needs 4*256 computations instead of 256^2.

### CODE REVIEW

**Comment by cospectrum** [comment]
Why not replace `f64::EPSILON` with `0.0`?

**Comment by theotherphil** [comment]
Thanks! Please can you make the change suggested by clippy (not obviously an improvement, but not worse and this is easier than ad-hoc disabling of lints) and then I’ll merge.

**Comment by cospectrum** [comment]
I will make a PR to lock the nightly channel for `clippy`

**Comment by oqpvc** [comment]
> Thanks! Please can you make the change suggested by clippy (not obviously an improvement, but not worse and this is easier than ad-hoc disabling of lints) and then I’ll merge.

I can absolutely do that, but just for the record: The clippy change is about code that has nothing to do with the PR. You still want me to push it here?

**Comment by theotherphil** [comment]
Ah, I hadn’t spotted that. Fixed by @cospectrum in https://github.com/image-rs/imageproc/pull/700.

Thanks for the new feature.

**Pull request merged**
